# Generated by Django 4.0.6 on 2022-07-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivtrol_analyzer',
            name='IDK',
            field=models.FileField(default='O', upload_to=''),
            preserve_default=False,
        ),
    ]
