# Generated by Django 4.0.6 on 2022-07-10 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Analysis', '0002_vivtrol_analyzer_idk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vivtrol_analyzer',
            old_name='IDK',
            new_name='File to Be Uploaded',
        ),
    ]
